version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
  backend:
    container_name: api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
