version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - postgres-db:/var/lib/postgresql/data
  backend:
    container_name: api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres-db:
    name: postgres-db
